### ISSUE TITLE
关于树的最末级节点的前缀样式

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#10]
![image](https://user-images.githubusercontent.com/34478822/37191606-ad524f12-239b-11e8-9e65-f44e69bf282d.png)

希望在树的最末级（没有子节点的时候）的前缀不显示任何图片样式。

**Comment by panlihai** [comment]
ant design的规范中是包含此样式的，待组件相对稳定后，根据实际情况着手修改样式。
