### ISSUE TITLE
关于导航条的头部ICON图标做成按钮,并实现单击后收放侧面菜单

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#11]
![image](https://user-images.githubusercontent.com/34478822/37195924-b6fd8176-23af-11e8-9f5d-56003ed47d00.png)
![image](https://user-images.githubusercontent.com/34478822/37195942-c8588862-23af-11e8-851a-b0271c0e1f8d.png)
左上角这个ICON图标可以做成ICON按钮嘛，实现点击后，能把菜单收回去的这种。

**Comment by panlihai** [comment]
增强型实现，将安排着手开发。

**Comment by panlihai** [comment]
完成开发，在底部实现收起。
