### ISSUE TITLE
关于fc-switch组件在预算项目中使用时报错

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#13]
![image](https://user-images.githubusercontent.com/34478822/37316502-7970b146-269a-11e8-8f65-8d12440ddf5a.png)

![image](https://user-images.githubusercontent.com/34478822/37316467-452d7f18-269a-11e8-90dd-7a10956a87e9.png)
![image](https://user-images.githubusercontent.com/34478822/37316470-4941b4e8-269a-11e8-9e2f-de26d48a804b.png)
  fc-switch 组件 在全面预算项目中 使用时 会报个错。

**Comment by panlihai** [comment]
已安排开发跟进。
