### ISSUE TITLE
关于fc-layoutrow 的fcSpan 在实际使用中还是没有生效。 

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#14]
fc-layoutrow 的fcSpan 在实际使用中还是没有生效。 
![image](https://user-images.githubusercontent.com/34478822/37316524-92a12056-269a-11e8-953b-94fdb423ba15.png)
由于这个功能限制了这个布局元素的高度，导致我的布局元素显示不出来,我试着临时注释了31行。但是这样便享受不到默认在不给定fcSpans属性的值时，默认给定的高50px了。

**Comment by panlihai** [comment]
@luohong123 处理一下此异常。

**Comment by windivi** [comment]
这个已经在新版本的Fccomponent中解决了。谢谢
