### ISSUE TITLE
关于页面样式，在进行一定页面切换操作后会发生改动

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#15]
还有个问题就是 
页面 刷新时 是这样的
![image](https://user-images.githubusercontent.com/34478822/37316562-d6412a18-269a-11e8-8a8f-9c9e0fbee04a.png)

在进行一定的页面切换操作回来后
![image](https://user-images.githubusercontent.com/34478822/37316567-dbb8d6d0-269a-11e8-8a31-c11786c176fb.png)

页面样式 有个 改动,看起来就像时切换回来后的布局才是想要的。
_____________________________________________________________________________

**Comment by panlihai** [comment]
此问题正在查找问题，应该是在新版本中已经解决。
