### ISSUE TITLE
首页的图标问题

### ISSUE THREAD

**Issue by fangkun202303** [panlihai/fcexample#16]
一:环境:
       1.数据库:最新的数据库表,数据      
       2.前台:    老平台
二:问题:     老平台首页的模块图标有丢失的
       
![qq 20180313103627](https://user-images.githubusercontent.com/33311937/37319646-f463de36-26aa-11e8-9de3-c0b5f941fee6.png)
       新平台是没有,数据库中有相应的数据的

![qq 20180313103610](https://user-images.githubusercontent.com/33311937/37319757-5b5dd60a-26ab-11e8-95d4-458d275f9d24.png)

**Comment by panlihai** [comment]
正在构建图标库，敬请期待吧，老铁
