### ISSUE TITLE
页面使用自定义表单的时候会出现新增与修改的问题

### ISSUE THREAD

**Issue by fangkun202303** [panlihai/fcexample#18]
1.新增:因为save方法保存的是Object对象,但是,自定义表单在点击"保存返回"是会出现mainObj对象是这样的,需要重写方法处理
![qq 20180313145538](https://user-images.githubusercontent.com/33311937/37331995-78752998-26e0-11e8-9196-ccbcd9a1a17d.png)
2.修改:
点击修改的时候需将列表回去的mainObj对象转成类似新增保存时的对象,要不然不会进行数据的回显
![qq 20180313170743](https://user-images.githubusercontent.com/33311937/37332247-13e33ba4-26e1-11e8-8dba-45116fbb7dc6.png)

如果使用的是fc-adform标签的话没这些问题

**Comment by panlihai** [comment]
此问题未正确的使用mainObj对象，mainObj对象旨在保存或修改主数据，此数据不绑定其它字典信息，其它自定义数据请使用别的变量声明。
