### ISSUE TITLE
自定义表单中的按钮问题

### ISSUE THREAD

**Issue by fangkun202303** [panlihai/fcexample#19]
表单用的是fc-adform是没问题的
自定义表单使用fc-tlbform标签获取的按钮,不会进入FcadformComponent中的事件处理,会进入ParentComponent中的事件处理,这样使表单的数据不能保存

**Comment by panlihai** [comment]
自定义表单使用fc-tlbform事件会通过parantCompoent处理，同时在当前组件的event中可以捕获，也就是说自定义的表单及fc-tlbform是需要自己在event中处理的。
