### ISSUE TITLE
基础服务平台-是否可以按照产品进行过滤 

### ISSUE THREAD

**Issue by qinjian2018** [panlihai/fcexample#21]
在基础服务平台中，配置元数据等界面时，是否可以根据产品进行过滤一下，比如：配置元数据时，通过产品选择我负责的产品之后，数据过滤之后，方便查找编辑我负责产品的内容。
        谢谢。

**Comment by panlihai** [comment]
尽快着手新版本的基础服务平台，将实现过滤修改等功能。
