### ISSUE TITLE
fcOption动态问题

### ISSUE THREAD

**Issue by fangkun202303** [panlihai/fcexample#22]
预警设置模块:
新增设置的时候,表单下面的列表是不能有操作列的,所以我在addNew方法中将fcEnableAction,fcCheckboxSelection的值变成false,当我点击修改的时候会将这两个值变成true在listEdit方法中,
可是这样会使fcOption只加载一次,值变不了,
现象:1.当先点击的是新增的时候会将操作列隐藏,再点击修改的时候操作列还是隐藏的,没有显示
        2.单先点击修改是,情况与之相反
![qq 20180322150232](https://user-images.githubusercontent.com/33311937/37755838-18bcc8ea-2de2-11e8-9dca-1dfc63537def.png)
![qq 20180322150246](https://user-images.githubusercontent.com/33311937/37755839-18f725a8-2de2-11e8-84c4-e8a1cefcf274.png)

**Comment by panlihai** [comment]
此问题估计是程序执行次序问题，建议在init或者是contructor方法中默认隐藏操作列。若还有异常，请联系...
