### ISSUE TITLE
页面导航问题

### ISSUE THREAD

**Issue by fangkun202303** [panlihai/fcexample#23]
问题:
当我们展开好几个页面的时候会出现导航条的标签与页面的情况不符合
![_20180322164256](https://user-images.githubusercontent.com/33311937/37760197-f10bf00a-2df0-11e8-87ff-f9557cefecae.png)
会切到首页
![_20180322164314](https://user-images.githubusercontent.com/33311937/37760199-f146f97a-2df0-11e8-9dec-509de57465f3.png)
当点击预算项目的时候会出现预算科目的页面,左侧的菜单显示的是预算项目;当再次点击预算项目时,页面是预算项目的页面,导航不是,此时的路径是对的
![_20180322164327](https://user-images.githubusercontent.com/33311937/37760201-f1805404-2df0-11e8-9a41-f94f5d0e349b.png)

**Comment by panlihai** [comment]
0.6.0版本后修复异常。
