### ISSUE TITLE
【利息资本化】-【起止条件类-查询、以及模糊查询时，传入where条件如何处理】

### ISSUE THREAD

**Issue by qinjian2018** [panlihai/fcexample#25]
![image](https://user-images.githubusercontent.com/36724684/37812607-ca4caa08-2e9b-11e8-80f8-9164146b9464.png)

**Comment by panlihai** [comment]
请咨询罗红，或者借鉴债权项目组的开发代码，所有查询条件绑定searchObj,你这种情况不需要绑定searchObj对象，在getDefaultQuery中返回对象，里面包含WHERE 中写期间条件。
