### ISSUE TITLE
【利息资本化】-【Gird操作列是否可以修改为 动态链接（带图标）目前都是按钮】

### ISSUE THREAD

**Issue by qinjian2018** [panlihai/fcexample#26]
![image](https://user-images.githubusercontent.com/36724684/37812670-1be5eb9a-2e9c-11e8-8063-a450a33e9e4d.png)

**Comment by luohong123** [comment]
现在平台提供的是按钮方式，图标库fc-icon正在完善中，待图标完善后会支持动态链接（带图标）方式
