### ISSUE TITLE
【利息资本化】-【Grid列最后一列是否可以自适应宽度】

### ISSUE THREAD

**Issue by qinjian2018** [panlihai/fcexample#27]
![image](https://user-images.githubusercontent.com/36724684/37812747-932c4596-2e9c-11e8-8714-c6dbe1d997bb.png)

**Comment by luohong123** [comment]
暂时不行，可以在基础服务平台里面手动设置宽度

**Comment by qinjian2018** [comment]
能自适应吗？分辨率不同的话，能设置吗？
