### ISSUE TITLE
npm ERR! Unexpected token < in JSON at position 119514

### ISSUE THREAD

**Issue by mengzhaojie** [panlihai/fcexample#3]
$ npm install
npm ERR! Unexpected token < in JSON at position 119514

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2018-02-02T07_29_16_930Z-debug.log

**Comment by luohong123** [comment]
解决方案，请跳转到此链接：https://github.com/panlihai/fcexample/issues/2
