### ISSUE TITLE
fc-checkbox 需要选中一个以完成全选的功能需求

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#37]
fc-checkbox 需要选中一个以达到全选的功能需求
![qq 20180328091810](https://user-images.githubusercontent.com/34478822/38003219-1be07a40-3269-11e8-82ce-e30cfd2837e9.png)

**Comment by luohong123** [comment]
这个是具体的业务，平台不支持这样的功能

**Comment by panlihai** [comment]
此为业务实现，不是平台功能，请利用其中的一个选中的事件，触发另外几个的数据绑定。
