### ISSUE TITLE
关于listdata如何填充

### ISSUE THREAD

**Issue by sleepyfighter** [panlihai/fcexample#40]
在后端使用sql查找好了数据，但是弄不到list里面去
![appobjects](https://user-images.githubusercontent.com/37787015/38452535-b01c37f0-3a78-11e8-972c-5c01dfd0ab8b.png)
![appobjects](https://user-images.githubusercontent.com/37787015/38452536-b0ba2fbe-3a78-11e8-8a65-335cef8283c2.png)
结果还是暂无数据，能不能给一个实例参考啊？

**Comment by panlihai** [comment]
请参考fclistdata.js实现。

**Comment by panlihai** [comment]
fcrowdata属性是填充列，fcOption.fields是填充字段。
