### ISSUE TITLE
 no exported member 'FcbandModule'.

### ISSUE THREAD

**Issue by ChangXingGuang** [panlihai/fcexample#5]
启动项目报错
ERROR in src/app/feature/basic/index.module.ts(6,81): error TS2305: Module '"C:/chang/全面预算/fcexample/node_module

**Comment by panlihai** [comment]
升级fccomponent到最新版本，npm i fccompoent@0.2.18版本即可解决问题，当出现问题的时候先删除node_modules 之后出现npm i
