### ISSUE TITLE
关于Fctree判断有无子节点的数据字段

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#6]
在全面预算项目中使用的树结构判断有无子节点的字段:BLAST(是否末级)与平台中使用的树结构判断有无子节点的树结构判断有无子节点的字段:HASCHILD(有无子节点)。存在是否意义上的冲突。

**Comment by panlihai** [comment]
fc-tree组件的fcOption中增加fcLeafValue的配置，默认为N，配置为Y是则指代是否末级。
