### ISSUE TITLE
关于新增树形下拉框组件

### ISSUE THREAD

**Issue by windivi** [panlihai/fcexample#9]
全面预算项目需要用到树形结构的下拉框组件，需要平台集成提供。
![image](https://user-images.githubusercontent.com/34478822/37143756-08cad364-22f7-11e8-996f-4b5a9eede361.png)
类似于这样

**Comment by panlihai** [comment]
这个组件已经调研，会在下一个升级版本中实现。

**Comment by panlihai** [comment]
此组件正在开发。一到两天完成开发。
